language: go
go_import_path: github.com/jjeffery/mechturk
go:
  - 1.4.3
  - 1.5.4
  - 1.6.2
  - tip

install:
  - go get github.com/aws/aws-sdk-go/aws/util
  - go get github.com/pkg/errors
  - go get github.com/spf13/cobra

script:
  - go test -v ./...
