language: go
go_import_path: github.com/jjeffery/mechturk
go:
  - 1.4.3
  - 1.5.4
  - 1.6.2
  - tip

install:
  - go get github.com/aws/aws-sdk-go/aws/awsutil
  - go get github.com/pkg/errors
  - go get github.com/spf13/cobra
  - go get github.com/stretchr/testify/assert

script:
  - go test -v ./...
